apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: argocd-private-key
  namespace: argocd
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  data:
    - key: argocd/private_key
      name: private_key
---
  apiVersion: 'kubernetes-client.io/v1'
  kind: ExternalSecret
  metadata:
    name: argocd-private-key
    namespace: argo-events
  spec:
    backendType: secretsManager
    # optional: specify role to assume when retrieving the data
    data:
      - key: argo-events
        name: argo-events     