apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: git@github.com:danielleffler/node-app-manifests.git
    targetRevision: HEAD
    path: deploy

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated: {}